apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: mayursuccessive/kubectl
            args: ["-c","./demo.sh"]
          restartPolicy: OnFailure



           
