apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellonode-deployment
  labels:
    app: hellonode
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hellonode
  template:
    metadata:
      labels:
        app: hellonode
    spec:
      containers:
      - name: hellonode-container
        image: mayursuccessive/hellonode:54361bf
        ports:
        - containerPort: 80